- hosts: all
  become: yes
  roles:
  - common
  - role: Load_Balancer
    vars:
      install_directory: /opt/static-website-example
      git_repository: https://gitlab.com/qacdevops/static-website-example
